### ISSUE TITLE
tag for version on packagist.org

### ISSUE THREAD

**Issue by azine** [excelwebzone/EWZSearchBundle#3]
Hey,

Could you add a tag to this git-repository (and also https://github.com/excelwebzone/zend-search )  and update your package on packagist.org.

That would remove the need of requiring your package @dev
when using composer, which is a very bad practice.

Sincerely,
Dominik

**Comment by azine** [comment]
Hi,

how about creating a tag (e.g. 1.0.0) as x-mas present for your users? ;-)

Happy holiday season!

Cheers,
d.

**Comment by azine** [comment]
Thanx for adding the tag to the excelwebzone/zend-search ..how about adding one here too. ;-)

**Comment by excelwebzone** [comment]
Done.
